import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const client=fs.readFileSync('cinematics.js','utf8');
const css=fs.readFileSync('atmosphere.css','utf8');
assert.match(html,/id="cinematicStage"/);
assert.match(html,/id="cinematicVignette"/);
assert.match(html,/LIVING CINEMATIC MODE/);
assert.match(client,/game:scene-ready/);
assert.match(client,/prefers-reduced-motion/);
assert.match(client,/sourceTurn%4===0/);
assert.match(client,/localStorage/);
assert.match(client,/duration=reduceMotion\?2800:7600/);
assert.doesNotMatch(client,/\/api\/cinematic/);
assert.doesNotMatch(client,/fetch\(/);
assert.match(css,/@keyframes livingCamera/);
assert.match(css,/@keyframes livingLight/);
assert.match(css,/prefers-reduced-motion/);
console.log('Living Cinematic Mode: instant, replayable and zero-cost: PASS');
