import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const client=fs.readFileSync('cinematics.js','utf8');
const api=fs.readFileSync('api/cinematic.js','utf8');
const migration=fs.readFileSync('supabase/migrations/20260831053212_selective_cinematic_mode.sql','utf8');
assert.match(html,/id="cinematicStage"/);
assert.match(html,/id="cinematicVideo"/);
assert.match(html,/cinematics\.js/);
assert.match(client,/game:scene-ready/);
assert.match(client,/prefers-reduced-motion/);
assert.match(client,/sourceTurn%4===0/);
assert.match(client,/\/api\/cinematic/);
assert.match(api,/experimental_startVideo/);
assert.match(api,/experimental_getVideoStatus/);
assert.match(api,/google\/veo-3\.1-lite-generate-001/);
assert.match(api,/duration:4/);
assert.match(api,/campaign_members/);
assert.match(api,/providerOptions:\{gateway:/);
assert.match(migration,/create table public\.cinematic_jobs/);
assert.match(migration,/enable row level security/);
assert.match(migration,/private\.is_campaign_member/);
assert.match(migration,/v_count >= 3/);
assert.match(migration,/unique\(campaign_id,source_turn\)/);
assert.match(migration,/revoke all on function public\.transition_cinematic_job/);
console.log('Selective Cinematic Mode: async generation, caching, RLS and cost limits: PASS');
