import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const j=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const clean=(x:unknown,n=160)=>String(x??'').replace(/\s+/g,' ').trim().slice(0,n);
const hex=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const d20=()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]%20)+1};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return j({error:'method_not_allowed'},405);
 const auth=req.headers.get('Authorization')||'',url=Deno.env.get('SUPABASE_URL')!;const userDb=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}}),admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const {data:{user}}=await userDb.auth.getUser();if(!user)return j({error:'unauthorized'},401);
 const b=await req.json().catch(()=>({})),campaignId=clean(b.campaign_id,80),op=clean(b.op,80),requestId=clean(b.client_request_id,120);if(!campaignId||!op||!requestId)return j({error:'campaign_id_op_and_client_request_id_required'},400);
 const {data:role}=await userDb.rpc('campaign_role',{p_campaign_id:campaignId});if(!role)return j({error:'campaign_access_denied'},403);const manage=role==='OWNER'||role==='GM',play=manage||role==='PLAYER';
 const idem=`game:${requestId}`;const {data:prior}=await userDb.from('game_audit_log').select('decision').eq('campaign_id',campaignId).eq('idempotency_key',idem).maybeSingle();if(prior?.decision?.result)return j({...prior.decision.result,replayed:true});
 let result:any={op};
 if(op==='character.create'){
   if(!play)return j({error:'player_role_required'},403);const name=clean(b.name,80),archetype=clean(b.archetype,80)||'wanderer';if(!name)return j({error:'name_required'},400);
   const {data:e,error}=await admin.from('campaign_entities').insert({campaign_id:campaignId,entity_type:'PC',name,state:{archetype,status:'active',controlled_by:user.id}}).select('id,name,state').single();if(error)return j({error:'character_create_failed'},400);
   await admin.from('character_stats').insert({entity_id:e.id,campaign_id:campaignId});await admin.from('inventory_items').insert({campaign_id:campaignId,owner_entity_id:e.id,name:'Traveler kit',item_type:'KIT',quantity:1,state:{starter:true}});result={op,character:e};
 } else if(op==='inventory.equip'){
   if(!play)return j({error:'player_role_required'},403);const itemId=clean(b.item_id,80),slot=clean(b.slot,30);if(!['HEAD','BODY','MAIN_HAND','OFF_HAND','ACCESSORY'].includes(slot))return j({error:'invalid_slot'},400);
   const {data:item}=await userDb.from('inventory_items').select('id,owner_entity_id').eq('campaign_id',campaignId).eq('id',itemId).single();if(!item)return j({error:'item_not_found'},404);const {data:entity}=await userDb.from('campaign_entities').select('state').eq('id',item.owner_entity_id).single();if(!manage&&entity?.state?.controlled_by!==user.id)return j({error:'not_character_controller'},403);
   await admin.from('inventory_items').update({equipped_slot:null,updated_at:new Date().toISOString()}).eq('owner_entity_id',item.owner_entity_id).eq('equipped_slot',slot);await admin.from('inventory_items').update({equipped_slot:slot,updated_at:new Date().toISOString()}).eq('id',itemId);result={op,item_id:itemId,slot};
 } else if(op==='npc.create'){
   if(!manage)return j({error:'gm_role_required'},403);const name=clean(b.name,80);if(!name)return j({error:'name_required'},400);const {data:e}=await admin.from('campaign_entities').insert({campaign_id:campaignId,entity_type:'NPC',name,state:{status:'active'}}).select('id,name').single();await admin.from('character_stats').insert({entity_id:e.id,campaign_id:campaignId,hp:Number(b.hp)||10,max_hp:Number(b.hp)||10,armor:Number(b.armor)||10,attack:Number(b.attack)||2});await admin.from('npc_agendas').insert({entity_id:e.id,campaign_id:campaignId,agenda:clean(b.agenda,160)||'observe',disposition:Math.max(-100,Math.min(100,Number(b.disposition)||0))});result={op,npc:e};
 } else if(op==='combat.start'){
   if(!manage)return j({error:'gm_role_required'},403);const ids=Array.isArray(b.entity_ids)?b.entity_ids.map((x:any)=>clean(x,80)).filter(Boolean).slice(0,20):[];if(ids.length<2)return j({error:'two_participants_required'},400);const {data:entities}=await userDb.from('campaign_entities').select('id,entity_type').eq('campaign_id',campaignId).in('id',ids);if((entities||[]).length!==ids.length)return j({error:'participant_not_found'},400);const {data:enc}=await admin.from('combat_encounters').insert({campaign_id:campaignId,state:{created_by:user.id}}).select('id').single();for(const e of entities||[])await admin.from('combat_participants').insert({encounter_id:enc.id,entity_id:e.id,initiative:d20(),side:e.entity_type==='PC'?'PARTY':'OPPOSITION'});result={op,encounter_id:enc.id};
 } else if(op==='combat.attack'){
   if(!play)return j({error:'player_role_required'},403);const encounterId=clean(b.encounter_id,80),attackerId=clean(b.attacker_id,80),defenderId=clean(b.defender_id,80);const {data:enc}=await userDb.from('combat_encounters').select('id,status').eq('campaign_id',campaignId).eq('id',encounterId).single();if(!enc||enc.status!=='ACTIVE')return j({error:'active_encounter_required'},400);const {data:attEnt}=await userDb.from('campaign_entities').select('state').eq('id',attackerId).single();if(!manage&&attEnt?.state?.controlled_by!==user.id)return j({error:'not_character_controller'},403);const [{data:a},{data:d}]=await Promise.all([userDb.from('character_stats').select('*').eq('campaign_id',campaignId).eq('entity_id',attackerId).single(),userDb.from('character_stats').select('*').eq('campaign_id',campaignId).eq('entity_id',defenderId).single()]);if(!a||!d)return j({error:'combatant_stats_missing'},400);const roll=d20(),damageRoll=Math.max(1,(d20()%6)+1),total=roll+a.attack,critical=roll===20,hit=roll!==1&&(critical||total>=d.armor),damage=hit?(damageRoll+(critical?damageRoll:0)):0,nextHp=Math.max(0,d.hp-damage);await admin.from('character_stats').update({hp:nextHp,updated_at:new Date().toISOString()}).eq('entity_id',defenderId);await admin.from('game_events').insert({campaign_id:campaignId,event_type:'COMBAT_ATTACK',payload:{encounter_id:encounterId,attacker_id:attackerId,defender_id:defenderId,roll,total,hit,critical,damage,defender_hp:nextHp}});if(nextHp===0)await admin.from('combat_participants').update({active:false}).eq('encounter_id',encounterId).eq('entity_id',defenderId);result={op,roll,total,hit,critical,damage,defender_hp:nextHp,defeated:nextHp===0};
 } else if(op==='ruleset.update'){
   if(!manage)return j({error:'gm_role_required'},403);const cfg=(b.config&&typeof b.config==='object')?b.config:{};const safe={dice:'d20',base_hp:Math.max(1,Math.min(999,Number(cfg.base_hp)||10)),critical_hit:20,critical_fail:1,round_seconds:Math.max(1,Math.min(3600,Number(cfg.round_seconds)||6)),turn_minutes:Math.max(1,Math.min(1440,Number(cfg.turn_minutes)||10)),max_inventory_slots:Math.max(1,Math.min(100,Number(cfg.max_inventory_slots)||20))};await admin.from('campaign_rulesets').upsert({campaign_id:campaignId,ruleset_id:'core-v1',config:safe,updated_at:new Date().toISOString()});result={op,config:safe};
 } else if(op==='quest.link'){
   if(!manage)return j({error:'gm_role_required'},403);const from=clean(b.from_quest_id,80),to=clean(b.to_quest_id,80),edge=clean(b.edge_type,30)||'UNLOCKS';if(!from||!to||from===to||!['UNLOCKS','REQUIRES','BLOCKS','BRANCHES_TO'].includes(edge))return j({error:'invalid_quest_edge'},400);const {data:q}=await userDb.from('campaign_quests').select('id').eq('campaign_id',campaignId).in('id',[from,to]);if((q||[]).length!==2)return j({error:'quest_not_found'},404);await admin.from('quest_edges').upsert({campaign_id:campaignId,from_quest_id:from,to_quest_id:to,edge_type:edge});result={op,from_quest_id:from,to_quest_id:to,edge_type:edge};
 } else if(op==='invite.create'){
   if(!manage)return j({error:'gm_role_required'},403);const inviteRole=['GM','PLAYER','SPECTATOR'].includes(b.role)?b.role:'PLAYER',code=`GP-${crypto.randomUUID().replaceAll('-','').slice(0,16).toUpperCase()}`,digest=await hex(code);await admin.from('campaign_invites').insert({campaign_id:campaignId,code_digest:digest,role:inviteRole,created_by:user.id,max_uses:Math.max(1,Math.min(100,Number(b.max_uses)||1)),expires_at:b.expires_at||null});result={op,code,role:inviteRole};
 } else return j({error:'unsupported_operation'},400);
 await admin.from('game_audit_log').insert({campaign_id:campaignId,correlation_id:requestId,idempotency_key:idem,action_type:`game.${op}`,policy_state:manage?'BOUNDED_AUTO':'AUTO',envelope:{tenant_id:campaignId,actor:{type:'USER',id:user.id,role},action:`game.${op}`,parameters:{},context:{},correlation_id:requestId,idempotency_key:idem,schema_version:'1',timestamp:new Date().toISOString()},decision:{reason:'game_systems_v2_authority',result}});
 return j(result);
});
