import assert from 'node:assert/strict';
import { simulateScenario, asPortfolioEvent } from './portfolioSimulation.js';
const a=simulateScenario({seed:'same',iterations:100,baseline:10,volatility:2});
const b=simulateScenario({seed:'same',iterations:100,baseline:10,volatility:2});
assert.deepEqual(a.metrics,b.metrics);
assert.equal(a.simulation_id,b.simulation_id);
assert.equal(a.authoritative,false);
const event=asPortfolioEvent(a,'corr-1');
assert.equal(event.event_type,'game.simulation.completed');
assert.equal(event.evidence_level,'E1');
const compared=simulateScenario({id:'comparison',seed:42,iterations:100,strategies:[{id:'a',parameters:{baseline:1}},{id:'b',parameters:{baseline:2}}],assumptions:['synthetic only']});
assert.equal(compared.results.length,2);assert.equal(compared.real_world_proof,false);
console.log('portfolio simulation tests passed');
