const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
export const DEFAULT_RULESET=Object.freeze({id:'core-v1',dice:'d20',base_hp:10,critical_hit:20,critical_fail:1,round_seconds:6,turn_minutes:10,max_inventory_slots:20});
export function normalizeStats(input={}){return{level:clamp(input.level||1,1,20),hp:clamp(input.hp??10,0,999),max_hp:clamp(input.max_hp??10,1,999),armor:clamp(input.armor??10,0,50),attack:clamp(input.attack??2,-10,30),speed:clamp(input.speed??30,0,200),conditions:Array.isArray(input.conditions)?input.conditions.slice(0,20):[]};}
export function resolveAttack({attacker={},defender={},roll,damageRoll}){const a=normalizeStats(attacker),d=normalizeStats(defender);const r=clamp(roll,1,20),total=r+a.attack,critical=r===20,miss=r===1||(!critical&&total<d.armor);const damage=miss?0:Math.max(1,clamp(damageRoll,1,100)+(critical?clamp(damageRoll,1,100):0));const hp=Math.max(0,d.hp-damage);return{roll:r,total,hit:!miss,critical,damage,defender_hp:hp,defeated:hp===0};}
export function equipItem({inventory=[],itemId,slot}){const allowed=new Set(['HEAD','BODY','MAIN_HAND','OFF_HAND','ACCESSORY']);const next=inventory.map(x=>({...x}));if(!allowed.has(slot))return{ok:false,reason:'invalid_slot',inventory:next};const item=next.find(x=>x.id===itemId);if(!item)return{ok:false,reason:'item_not_found',inventory:next};for(const x of next)if(x.equipped_slot===slot)x.equipped_slot=null;item.equipped_slot=slot;return{ok:true,inventory:next};}
export function advanceWorldClock(clock={day:1,hour:8,minute:0},minutes=10){let total=((clamp(clock.day||1,1,999999)-1)*1440)+(clamp(clock.hour,0,23)*60)+clamp(clock.minute,0,59)+clamp(minutes,0,10080);return{day:Math.floor(total/1440)+1,hour:Math.floor((total%1440)/60),minute:total%60};}
export function deriveNpcIntent(npc={},world={}){const agenda=npc.agenda||'observe';const disposition=clamp(npc.disposition??0,-100,100);const threat=clamp(world.threat_level??1,0,10);if(npc.hp===0)return{intent:'inactive',priority:0};if(disposition<=-50||threat>=8)return{intent:'confront',priority:9};if(disposition>=50)return{intent:'assist',priority:6};if(/trade|merchant/i.test(agenda))return{intent:'trade',priority:4};if(/guard|protect/i.test(agenda))return{intent:'patrol',priority:5};return{intent:'observe',priority:3};}
export function canManageCampaign(role){return role==='OWNER'||role==='GM';}
export function canPlayCampaign(role){return role==='OWNER'||role==='GM'||role==='PLAYER';}
export function canViewCampaign(role){return canPlayCampaign(role)||role==='SPECTATOR';}
export function validateQuestEdge(fromId,toId){return Boolean(fromId&&toId&&fromId!==toId);}
