-- Competitive AI runtime: authoritative matches, immutable telemetry, shared ratings and async risk flags.
create table if not exists public.competitive_matches (
  id uuid primary key default gen_random_uuid(), campaign_id uuid references public.campaigns(id) on delete set null,
  mode text not null, region text not null, status text not null default 'QUEUED' check(status in ('QUEUED','RUNNING','COMPLETED','ABORTED')),
  ruleset_version text not null, map_version text not null, random_seed bigint not null,
  started_at timestamptz, ended_at timestamptz, created_at timestamptz not null default now(),
  check(ended_at is null or started_at is null or ended_at >= started_at)
);
create table if not exists public.competitive_match_participants (
  match_id uuid not null references public.competitive_matches(id) on delete cascade, participant_id uuid not null,
  participant_type text not null check(participant_type in ('PLAYER','BOT')), team smallint not null check(team between 1 and 16),
  bot_version text, initial_rating integer, outcome real check(outcome between 0 and 1), joined_at timestamptz not null default now(),
  primary key(match_id,participant_id), check((participant_type='BOT' and bot_version is not null) or participant_type='PLAYER')
);
create table if not exists public.competitive_game_events (
  id uuid primary key, schema_version smallint not null default 1 check(schema_version=1),
  match_id uuid not null references public.competitive_matches(id) on delete cascade, actor_id uuid not null,
  event_type text not null, sequence bigint not null check(sequence>=0), source text not null check(source in ('GAME_SERVER','BOT_RUNTIME','SYSTEM_JOB')),
  occurred_at timestamptz not null, received_at timestamptz not null default now(), bot_version text, ruleset_version text,
  map_version text, random_seed bigint, payload jsonb not null default '{}'::jsonb check(jsonb_typeof(payload)='object'), unique(match_id,sequence)
);
create table if not exists public.player_skill_ratings (
  player_id uuid not null, queue text not null, region text not null,
  algorithm text not null default 'elo-v1' check(algorithm in ('elo-v1','glicko2-v1')), rating integer not null default 1500 check(rating between 0 and 4000),
  deviation real, volatility real, games integer not null default 0 check(games>=0), provisional boolean generated always as (games<10) stored,
  updated_at timestamptz not null default now(), primary key(player_id,queue,region)
);
create table if not exists public.competitive_risk_flags (
  id bigint generated by default as identity primary key, match_id uuid not null references public.competitive_matches(id) on delete cascade,
  actor_id uuid not null, risk_type text not null, severity text not null check(severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
  evidence jsonb not null default '{}'::jsonb check(jsonb_typeof(evidence)='object'), status text not null default 'OPEN' check(status in ('OPEN','REVIEWING','CONFIRMED','DISMISSED')),
  detected_at timestamptz not null default now(), reviewed_at timestamptz
);
create index if not exists competitive_matches_queue_idx on public.competitive_matches(region,mode,status,created_at);
create index if not exists competitive_participant_player_idx on public.competitive_match_participants(participant_id,joined_at desc) where participant_type='PLAYER';
create index if not exists competitive_events_replay_idx on public.competitive_game_events(match_id,sequence);
create index if not exists competitive_events_async_idx on public.competitive_game_events(received_at,event_type);
create index if not exists competitive_ratings_matchmaking_idx on public.player_skill_ratings(queue,region,rating);
create index if not exists competitive_risk_review_idx on public.competitive_risk_flags(status,severity,detected_at);
alter table public.competitive_matches enable row level security; alter table public.competitive_match_participants enable row level security;
alter table public.competitive_game_events enable row level security; alter table public.player_skill_ratings enable row level security; alter table public.competitive_risk_flags enable row level security;
alter table public.competitive_matches force row level security; alter table public.competitive_match_participants force row level security;
alter table public.competitive_game_events force row level security; alter table public.player_skill_ratings force row level security; alter table public.competitive_risk_flags force row level security;
revoke all on public.competitive_matches,public.competitive_match_participants,public.competitive_game_events,public.player_skill_ratings,public.competitive_risk_flags from public,anon,authenticated;
grant select on public.competitive_matches,public.competitive_match_participants,public.competitive_game_events,public.player_skill_ratings to authenticated;
create policy competitive_matches_participant_select on public.competitive_matches for select to authenticated using(exists(select 1 from public.competitive_match_participants p where p.match_id=id and p.participant_type='PLAYER' and p.participant_id=(select auth.uid())));
create policy competitive_participants_match_select on public.competitive_match_participants for select to authenticated using(exists(select 1 from public.competitive_match_participants self where self.match_id=competitive_match_participants.match_id and self.participant_type='PLAYER' and self.participant_id=(select auth.uid())));
create policy competitive_events_participant_select on public.competitive_game_events for select to authenticated using(exists(select 1 from public.competitive_match_participants p where p.match_id=competitive_game_events.match_id and p.participant_type='PLAYER' and p.participant_id=(select auth.uid())));
create policy skill_ratings_owner_select on public.player_skill_ratings for select to authenticated using(player_id=(select auth.uid()));
comment on table public.competitive_game_events is 'Append-only server-authored telemetry. Clients receive SELECT only; all writes use trusted server infrastructure.';
comment on table public.competitive_risk_flags is 'Out-of-band anomaly findings; deliberately unavailable through the player Data API.';
