alter table public.character_stats
  add column if not exists experience bigint not null default 0 check (experience >= 0),
  add column if not exists intelligence smallint not null default 10 check (intelligence between 1 and 30),
  add column if not exists stealth smallint not null default 10 check (stealth between 1 and 30),
  add column if not exists cunning smallint not null default 10 check (cunning between 1 and 30);

create table if not exists public.combat_kill_rewards (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  encounter_id uuid not null references public.combat_encounters(id) on delete cascade,
  killer_entity_id uuid not null references public.campaign_entities(id) on delete cascade,
  victim_entity_id uuid not null references public.campaign_entities(id) on delete cascade,
  experience_awarded integer not null check (experience_awarded > 0),
  created_at timestamptz not null default now(),
  unique (encounter_id, victim_entity_id)
);

alter table public.combat_kill_rewards enable row level security;
alter table public.combat_kill_rewards force row level security;
revoke all on table public.combat_kill_rewards from anon, authenticated;
grant all on table public.combat_kill_rewards to service_role;
grant usage, select on sequence public.combat_kill_rewards_id_seq to service_role;
