-- Living Characters: identity, durable memory, relationships and auditable actions.
create extension if not exists vector with schema extensions;

create table if not exists public.npcs (
  id uuid primary key references public.campaign_entities(id) on delete cascade,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  name text not null,
  personality_prompt text not null default 'Observant, self-directed, consistent with established characterisation.',
  base_objective text not null default 'Observe the world and protect personal interests.',
  current_objective text,
  emotional_state jsonb not null default '{"mood":"neutral","intensity":0}'::jsonb,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','INCAPACITATED','MISSING','DEAD','DEPARTED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(campaign_id,id)
);

create table if not exists public.npc_memory (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  npc_id uuid not null references public.npcs(id) on delete cascade,
  memory_type text not null check (memory_type in ('FACT','RELATIONSHIP','EVENT','PROMISE','SUSPICION','GOAL')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1536),
  importance real not null default 0.5 check (importance between 0 and 1),
  decay_weight real not null default 1 check (decay_weight between 0 and 1),
  occurred_at timestamptz not null default now(),
  last_recalled_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.npc_relationships (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  npc_id uuid not null references public.npcs(id) on delete cascade,
  target_type text not null check (target_type in ('PLAYER','NPC')),
  target_id uuid not null,
  score smallint not null default 0 check (score between -100 and 100),
  trust smallint not null default 0 check (trust between -100 and 100),
  fear smallint not null default 0 check (fear between 0 and 100),
  respect smallint not null default 0 check (respect between -100 and 100),
  last_updated timestamptz not null default now(),
  unique(campaign_id,npc_id,target_type,target_id)
);

create table if not exists public.npc_action_log (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  npc_id uuid not null references public.npcs(id) on delete cascade,
  tick_id bigint not null,
  proposed_action jsonb not null,
  validation_status text not null default 'PENDING' check (validation_status in ('PENDING','APPROVED','REJECTED','MODIFIED')),
  validation_reason text,
  outcome jsonb,
  created_at timestamptz not null default now(),
  unique(campaign_id,npc_id,tick_id)
);

create index if not exists npcs_campaign_idx on public.npcs(campaign_id,status);
create index if not exists npc_memory_lookup_idx on public.npc_memory(campaign_id,npc_id,memory_type,created_at desc);
create index if not exists npc_memory_embedding_idx on public.npc_memory using hnsw (embedding vector_cosine_ops) where embedding is not null;
create index if not exists npc_relationships_lookup_idx on public.npc_relationships(campaign_id,npc_id,score desc);
create index if not exists npc_action_log_tick_idx on public.npc_action_log(campaign_id,tick_id desc,npc_id);

alter table public.npcs enable row level security;
alter table public.npc_memory enable row level security;
alter table public.npc_relationships enable row level security;
alter table public.npc_action_log enable row level security;
alter table public.npcs force row level security;
alter table public.npc_memory force row level security;
alter table public.npc_relationships force row level security;
alter table public.npc_action_log force row level security;

revoke all on public.npcs,public.npc_memory,public.npc_relationships,public.npc_action_log from public,anon,authenticated;
grant select on public.npcs,public.npc_memory,public.npc_relationships,public.npc_action_log to authenticated;

drop policy if exists npcs_member_select on public.npcs;
create policy npcs_member_select on public.npcs for select to authenticated
using (public.is_campaign_member(campaign_id));
drop policy if exists npc_memory_member_select on public.npc_memory;
create policy npc_memory_member_select on public.npc_memory for select to authenticated
using (public.is_campaign_member(campaign_id));
drop policy if exists npc_relationships_member_select on public.npc_relationships;
create policy npc_relationships_member_select on public.npc_relationships for select to authenticated
using (public.is_campaign_member(campaign_id));
drop policy if exists npc_action_log_member_select on public.npc_action_log;
create policy npc_action_log_member_select on public.npc_action_log for select to authenticated
using (public.is_campaign_member(campaign_id));

create or replace function public.sync_living_npc()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $function$
declare a record;
begin
  if new.kind <> 'NPC' then return new; end if;
  select * into a from public.npc_agendas where entity_id=new.id;
  insert into public.npcs(id,campaign_id,name,personality_prompt,base_objective,current_objective,emotional_state,status,updated_at)
  values(new.id,new.campaign_id,new.name,
    coalesce(new.state->>'personality','Observant, self-directed, and consistent with established characterisation.'),
    coalesce(a.agenda,new.state->>'objective','Observe the world and protect personal interests.'),
    coalesce(a.agenda,new.state->>'objective'),
    jsonb_build_object('mood',case when coalesce(a.disposition,0)>20 then 'hopeful' when coalesce(a.disposition,0)<-20 then 'guarded' else 'neutral' end,'intensity',abs(coalesce(a.disposition,0))),
    case when new.state->>'status' in ('dead','DEAD') then 'DEAD' else 'ACTIVE' end,now())
  on conflict(id) do update set name=excluded.name,personality_prompt=excluded.personality_prompt,
    base_objective=excluded.base_objective,current_objective=excluded.current_objective,
    emotional_state=excluded.emotional_state,status=excluded.status,updated_at=now();
  return new;
end $function$;
revoke execute on function public.sync_living_npc() from public,anon,authenticated;

drop trigger if exists campaign_entities_sync_living_npc on public.campaign_entities;
create trigger campaign_entities_sync_living_npc after insert or update on public.campaign_entities
for each row execute function public.sync_living_npc();

insert into public.npcs(id,campaign_id,name,personality_prompt,base_objective,current_objective,emotional_state,status)
select e.id,e.campaign_id,e.name,
  coalesce(e.state->>'personality','Observant, self-directed, and consistent with established characterisation.'),
  coalesce(a.agenda,'Observe the world and protect personal interests.'),a.agenda,
  jsonb_build_object('mood',case when coalesce(a.disposition,0)>20 then 'hopeful' when coalesce(a.disposition,0)<-20 then 'guarded' else 'neutral' end,'intensity',abs(coalesce(a.disposition,0))),
  case when e.state->>'status' in ('dead','DEAD') then 'DEAD' else 'ACTIVE' end
from public.campaign_entities e left join public.npc_agendas a on a.entity_id=e.id
where e.kind='NPC'
on conflict(id) do update set name=excluded.name,personality_prompt=excluded.personality_prompt,
base_objective=excluded.base_objective,current_objective=excluded.current_objective,emotional_state=excluded.emotional_state,updated_at=now();

insert into public.npc_memory(campaign_id,npc_id,memory_type,content,metadata,importance,decay_weight)
select n.campaign_id,n.id,'FACT','My enduring objective is: '||n.base_objective,
jsonb_build_object('origin','living_characters_bootstrap'),0.9,1
from public.npcs n
where not exists(select 1 from public.npc_memory m where m.npc_id=n.id and m.metadata->>'origin'='living_characters_bootstrap');
