-- Conversion funnel telemetry and deterministic, ready-to-play starter worlds.
create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  campaign_id uuid references public.campaigns(id) on delete set null,
  event_name text not null check (event_name in (
    'game_platform_loaded','starter_world_viewed','starter_world_selected',
    'campaign_created','first_decision_completed','second_turn_completed','return_visit'
  )),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists product_events_name_created_idx
  on public.product_events(event_name, created_at desc);
create index if not exists product_events_user_created_idx
  on public.product_events(user_id, created_at desc);

alter table public.product_events enable row level security;
alter table public.product_events force row level security;
revoke all on public.product_events from public, anon, authenticated;
grant insert on public.product_events to authenticated;
grant usage, select on sequence public.product_events_id_seq to authenticated;
drop policy if exists product_events_own_insert on public.product_events;
create policy product_events_own_insert on public.product_events
  for insert to authenticated
  with check (user_id = (select auth.uid()));

create or replace function public.bootstrap_campaign_v2()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  starter text := coalesce(new.world_state->>'starter_id', case new.title
    when 'The Ashen Gate' then 'ashen-gate'
    when 'Neon After Midnight' then 'neon-midnight'
    when 'The Last Expedition' then 'last-expedition'
  end);
  hero_id uuid;
  npc_one_id uuid;
  npc_two_id uuid;
  session_id uuid;
  hero_name text;
  hero_archetype text;
  npc_one_name text;
  npc_one_agenda text;
  npc_two_name text;
  npc_two_agenda text;
  quest_title text;
  quest_text text;
  opening_text text;
  starter_state jsonb;
begin
  insert into public.campaign_members(campaign_id,user_id,role,status)
  values(new.id,new.owner_id,'OWNER','ACTIVE') on conflict do nothing;
  insert into public.campaign_rulesets(campaign_id,ruleset_id,config,updated_at)
  values(new.id,'core-v1','{"dice":"d20","base_hp":10,"critical_hit":20,"critical_fail":1,"round_seconds":6,"turn_minutes":10,"max_inventory_slots":20}'::jsonb,now()) on conflict do nothing;
  insert into public.world_clocks(campaign_id,day,hour,minute,tick_version,updated_at)
  values(new.id,1,8,0,0,now()) on conflict do nothing;

  if starter in ('ashen-gate','neon-midnight','last-expedition') then
    insert into public.product_events(user_id,campaign_id,event_name,properties)
      values
        (new.owner_id,new.id,'starter_world_selected',jsonb_build_object('starter_id',starter)),
        (new.owner_id,new.id,'campaign_created',jsonb_build_object('starter_id',starter,'mode','instant'));
    if starter = 'ashen-gate' then
      hero_name := 'Mara Vey'; hero_archetype := 'Oathbroken Gate Warden';
      npc_one_name := 'Captain Ilyan Rook'; npc_one_agenda := 'Seal the gate before the truth enters the city';
      npc_two_name := 'Sable'; npc_two_agenda := 'Reach Mara and expose who truly built the Ashen Gate';
      quest_title := 'The Last Knock'; quest_text := 'Decide who crosses before the Ashen Gate seals forever.';
      opening_text := 'The Ashen Gate is already descending when the stranger outside removes her hood. She has your eyes—and your dead mother’s signet. Behind her, shapes race through the red dust. Captain Rook orders you to turn the final key. You have seconds.';
      starter_state := '{"genre":"dark fantasy survival","location":"the Ashen Gate beneath a blood-red dawn","threat_level":4,"opening_label":"The gate is closing","choices":["Hold the gate and pull the stranger inside.","Obey Captain Rook and turn the final key.","Demand the signet as proof before choosing."]}'::jsonb;
    elsif starter = 'neon-midnight' then
      hero_name := 'Juno Vale'; hero_archetype := 'Memory Forensics Detective';
      npc_one_name := 'Inspector Orin Kade'; npc_one_agenda := 'Erase the train and everyone who remembers the coming coup';
      npc_two_name := 'Nia-7'; npc_two_agenda := 'Protect the passengers long enough to make their future public';
      quest_title := 'Seven Years Late'; quest_text := 'Learn why the impossible train knows your future before security purges Platform Nine.';
      opening_text := 'At 00:07, a train missing for seven years glides into Platform Nine. Its passengers step into the rain without having aged. One presses a blood-warm data shard into your hand: footage of you assassinating the mayor tomorrow. Security shutters begin to fall.';
      starter_state := '{"genre":"noir science-fiction mystery","location":"Platform Nine in the rain-soaked city of Vanta","threat_level":4,"opening_label":"The future just arrived","choices":["Hide the passenger and copy the data shard.","Hand the shard to Inspector Kade—but keep the passenger talking.","Broadcast one frame of the footage to the whole station."]}'::jsonb;
    else
      hero_name := 'Dr. Ren Sol'; hero_archetype := 'Rift Cartographer';
      npc_one_name := 'Commander Voss'; npc_one_agenda := 'Destroy the observatory before its discovery destabilizes the known world';
      npc_two_name := 'Tala Quill'; npc_two_agenda := 'Rescue the missing expedition, whatever came back with them';
      quest_title := 'Below the Impossible Sea'; quest_text := 'Reach the drowned observatory before the final transmission ends.';
      opening_text := 'Your missing expedition speaks through a receiver with no power. “Ren, do not let Voss sink us again.” Beyond the cliff, a new ocean hangs vertically in the sky, and the drowned observatory is visible beneath its surface. Commander Voss begins a five-minute demolition count.';
      starter_state := '{"genre":"lost-world exploration","location":"the drowned observatory at the edge of the map","threat_level":4,"opening_label":"Five minutes to the impossible sea","choices":["Leap through the vertical ocean with Tala.","Sabotage Voss’s detonator before approaching the rift.","Answer the transmission and ask what followed them home."]}'::jsonb;
    end if;

    update public.campaigns
      set world_state = coalesce(new.world_state,'{}'::jsonb) || starter_state || jsonb_build_object('starter_id',starter,'clock','Day 1 08:00')
      where id = new.id;
    insert into public.campaign_entities(campaign_id,kind,name,state)
      values(new.id,'PC',hero_name,jsonb_build_object('archetype',hero_archetype,'status','active','controlled_by',new.owner_id)) returning id into hero_id;
    insert into public.character_stats(entity_id,campaign_id,hp,max_hp,armor,attack) values(hero_id,new.id,12,12,12,3);
    insert into public.inventory_items(campaign_id,owner_entity_id,name,item_type,quantity,state)
      values(new.id,hero_id,'Story-critical field kit','KIT',1,'{"starter":true}'::jsonb);

    insert into public.campaign_entities(campaign_id,kind,name,state)
      values(new.id,'NPC',npc_one_name,'{"status":"active"}'::jsonb) returning id into npc_one_id;
    insert into public.character_stats(entity_id,campaign_id,hp,max_hp,armor,attack) values(npc_one_id,new.id,10,10,11,2);
    insert into public.npc_agendas(entity_id,campaign_id,agenda,disposition,state)
      values(npc_one_id,new.id,npc_one_agenda,-10,'{"competes_with":"starter_npc_two"}'::jsonb);

    insert into public.campaign_entities(campaign_id,kind,name,state)
      values(new.id,'NPC',npc_two_name,'{"status":"active"}'::jsonb) returning id into npc_two_id;
    insert into public.character_stats(entity_id,campaign_id,hp,max_hp,armor,attack) values(npc_two_id,new.id,10,10,11,2);
    insert into public.npc_agendas(entity_id,campaign_id,agenda,disposition,state)
      values(npc_two_id,new.id,npc_two_agenda,15,'{"competes_with":"starter_npc_one"}'::jsonb);

    insert into public.campaign_quests(campaign_id,title,status,objective,source_turn)
      values(new.id,quest_title,'OPEN',jsonb_build_object('text',quest_text),0);
    insert into public.game_sessions(campaign_id,status,turn_count,last_active_at)
      values(new.id,'ACTIVE',0,now()) returning id into session_id;
    insert into public.game_turns(session_id,campaign_id,turn_no,speaker,content,metadata)
      values(session_id,new.id,0,'GM',opening_text,'{"reasoner":"starter-director-v1","opening":true}'::jsonb);
    insert into public.campaign_memory(campaign_id,memory_type,content)
      values(new.id,'SEMANTIC',jsonb_build_object('summary',quest_text,'starter_id',starter));
  end if;
  return new;
end
$function$;

revoke execute on function public.bootstrap_campaign_v2() from public, anon, authenticated;

create or replace function public.track_starter_decision()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  actor uuid;
  decision_count integer;
  starter text;
begin
  if new.speaker <> 'PLAYER' then return new; end if;
  actor := nullif(new.metadata->>'user_id','')::uuid;
  select world_state->>'starter_id' into starter from public.campaigns where id=new.campaign_id;
  if actor is null or starter is null then return new; end if;
  select count(*) into decision_count from public.game_turns
    where campaign_id=new.campaign_id and speaker='PLAYER';
  if decision_count = 1 then
    insert into public.product_events(user_id,campaign_id,event_name,properties)
      values(actor,new.campaign_id,'first_decision_completed',jsonb_build_object('starter_id',starter,'turn_no',new.turn_no));
  elsif decision_count = 2 then
    insert into public.product_events(user_id,campaign_id,event_name,properties)
      values(actor,new.campaign_id,'second_turn_completed',jsonb_build_object('starter_id',starter,'turn_no',new.turn_no));
  end if;
  return new;
end
$function$;

revoke execute on function public.track_starter_decision() from public, anon, authenticated;
drop trigger if exists game_turns_track_starter_decision on public.game_turns;
create trigger game_turns_track_starter_decision
  after insert on public.game_turns
  for each row execute function public.track_starter_decision();
