const SUPABASE_URL='https://vtrfgckzpjgtmqsnumur.supabase.co';
const SUPABASE_KEY='sb_publishable_zsgA314WZue1tlu_Kt-SDQ_UopdKMNs';
const MODEL='openai/gpt-5.4-nano';
const FALLBACK_MODELS=['google/gemini-3.6-flash'];
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const outputText=response=>typeof response?.output_text==='string'?response.output_text:(response?.output||[]).filter(item=>item?.type==='message').flatMap(item=>item.content||[]).filter(item=>item?.type==='output_text'||item?.type==='text').map(item=>item.text||'').join('');
const narrativeSchema={type:'object',properties:{narrative:{type:'string',maxLength:900},choices:{type:'array',minItems:3,maxItems:3,uniqueItems:true,items:{type:'string',minLength:8,maxLength:160}},quest:{anyOf:[{type:'null'},{type:'object',properties:{op:{type:'string',enum:['create','resolve']},title:{type:'string'},objective:{type:'string'},status:{type:'string',enum:['OPEN','COMPLETED','FAILED']}},required:['op','title','objective','status'],additionalProperties:false}]},faction_updates:{type:'array',maxItems:4,items:{type:'object',properties:{name:{type:'string'},delta:{type:'integer',minimum:-10,maximum:10}},required:['name','delta'],additionalProperties:false}},npc_updates:{type:'array',maxItems:8,items:{type:'object',properties:{name:{type:'string'},agenda:{type:'string'},disposition_delta:{type:'integer',minimum:-5,maximum:5}},required:['name','agenda','disposition_delta'],additionalProperties:false}}},required:['narrative','choices','quest','faction_updates','npc_updates'],additionalProperties:false};
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});
 const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer '))return res.status(401).json({error:'unauthorized'});
 const u=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:auth}});if(!u.ok)return res.status(401).json({error:'unauthorized'});const user=await u.json();
 const body=req.body||{},campaignId=clean(body.campaign_id).slice(0,80);if(!campaignId)return res.status(400).json({error:'campaign_id_required'});
 const member=await fetch(`${SUPABASE_URL}/rest/v1/campaign_members?campaign_id=eq.${encodeURIComponent(campaignId)}&user_id=eq.${encodeURIComponent(user.id)}&status=eq.ACTIVE&select=role&limit=1`,{headers:{apikey:SUPABASE_KEY,Authorization:auth,Accept:'application/json'}});if(!member.ok)return res.status(403).json({error:'campaign_access_denied'});const memberships=await member.json();if(!['OWNER','GM','PLAYER'].includes(memberships?.[0]?.role))return res.status(403).json({error:'player_role_required'});
 const context=body.context||{},state=context?.campaign?.world_state||{},previousChoices=Array.isArray(state.choices)?state.choices.map(clean).filter(Boolean):[],lastAction=clean(context?.player_action),ctx=JSON.stringify(context).slice(0,18000);
 const prompt=`You are the AI GM for a persistent tabletop RPG. Continue the story forward from the player's selected action. Preserve canon, named characters, location, world time, NPC motivations, quests, factions, combat and checks. The selected action must cause a concrete visible consequence. Never reset or replay the previous scene. Return a vivid new situation and exactly three materially different next actions grounded in that new situation. Never reuse or lightly paraphrase a previous choice or the selected action. Previous choices: ${JSON.stringify(previousChoices)}. Selected action: ${JSON.stringify(lastAction)}. Progression: ${JSON.stringify(state.story_progression||{})}. Keep narrative <=900 characters. Each choice begins with an action verb. Campaign context: ${ctx}`;
 const token=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;if(!token)return res.status(503).json({error:'gateway_auth_unavailable'});
 try{const r=await fetch('https://ai-gateway.vercel.sh/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,input:prompt,max_output_tokens:1200,providerOptions:{gateway:{models:FALLBACK_MODELS}},text:{format:{type:'json_schema',name:'gm_turn',strict:true,schema:narrativeSchema}}}),signal:AbortSignal.timeout(25000)});if(!r.ok){const detail=clean(await r.text()).slice(0,500);console.error('[narrate] gateway request failed',{status:r.status,model:MODEL,detail});return res.status(503).json({error:'ai_gm_unavailable',status:r.status});}const raw=await r.json(),text=clean(outputText(raw));if(!text)throw new Error('empty_model_output');const out=JSON.parse(text);out.narrative=clean(out.narrative).slice(0,900);out.choices=Array.isArray(out.choices)?out.choices.map(x=>clean(x).slice(0,160)).filter(Boolean).slice(0,3):[];const forbidden=new Set([...previousChoices,lastAction].map(norm).filter(Boolean)),unique=new Set(out.choices.map(norm));if(out.choices.length!==3||unique.size!==3||out.choices.some(x=>forbidden.has(norm(x))))throw new Error('choices_repeat_previous_state');out.faction_updates=Array.isArray(out.faction_updates)?out.faction_updates.slice(0,4):[];out.npc_updates=Array.isArray(out.npc_updates)?out.npc_updates.slice(0,8):[];return res.status(200).json(out)}catch(error){console.error('[narrate] generation failed',{message:error instanceof Error?error.message:String(error)});return res.status(503).json({error:'ai_gm_unavailable'})}
}
